#!/bin/bash
set -e

source ./deploy.conf

sudo su -p <<HERE
set -e

# Set locale to C
echo 'LC_ALL=C' >> /etc/sysconfig/i18n
export LC_ALL=C

# yum packages
yum -y update
yum -y install $YUM_PACKAGES

# nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
source ~/.bashrc
nvm install $NODEJS_VERSION
nvm use $NODEJS_VERSION

# user www-data
mkdir -p $PROJECT_DIR
useradd www-data
usermod -a -G www-data ec2-user

# Extract project
tar -xzf /home/ec2-user/$PROJECT_NAME.tar.gz -C $PROJECT_DIR

# permissions
chown -R www-data:www-data $WEB_ROOT
chmod 2775 $WEB_ROOT
find $WEB_ROOT -type d -exec sudo chmod 2775 {} +
find $WEB_ROOT -type f -exec sudo chmod 0664 {} +

# npm
cd $PROJECT_DIR
npm install --save

# pm2
npm install -g pm2
pm2 start $PROJECT_DIR/server.js
pm2 save
pm2 startup amazon -u www-data
chmod u+x /etc/init.d/pm2-init.sh
chkconfig --add pm2-init.sh
chown -R www-data:www-data ~/

# nginx
yes | cp -rf $PROJECT_DIR/deploy/nginx.conf /etc/nginx
chkconfig nginx on

# service
service nginx start
HERE
