#!/bin/bash
set -e

source ./deploy.conf

sudo su -p <<HERE
set -e
source ~/.bashrc

# Extract project
tar -xzf /home/ec2-user/$PROJECT_NAME.tar.gz -C $PROJECT_DIR

# directory permission
chown -R www-data:www-data $WEB_ROOT
chmod 2775 $WEB_ROOT
find $WEB_ROOT -type d -exec sudo chmod 2775 {} +
find $WEB_ROOT -type f -exec sudo chmod 0664 {} +

# nginx
yes | cp -rf $PROJECT_DIR/deploy/nginx.conf /etc/nginx

# service
service nginx restart
service pm2-init.sh restart
HERE
